Fix exception handling error strings
We got the following exception because we didn't do `str(exc)`
```
Cannot get job status of 0cf471c7-049c-43f2-b9cd-08d3fe006e8b,
('NameError' object has no attribute 'get')
```